from mesa import Agent
from enum import Enum


# ---------------------------------------------------------------
class Infra(Agent):
    """
    Base class for all infrastructure components

    Attributes
    __________
    vehicle_count : int
        the number of vehicles that are currently in/on (or totally generated/removed by)
        this infrastructure component

    length : float
        the length in meters
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown'):
        super().__init__(unique_id, model)
        self.length = length
        self.name = name
        self.road_name = road_name
        self.vehicle_count = 0

    def step(self):
        pass

    def __str__(self):
        return type(self).__name__ + str(self.unique_id)


class Bridge(Infra):
    """
    Creates delay time

    Attributes
    __________
    condition:
        condition of the bridge

    delay_time: int
        the delay (in ticks) caused by this bridge
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown', condition='Unknown'):
        super().__init__(unique_id, model, length, name, road_name)

        self.condition = condition
        # New for BONUS: Track total delay caused by this bridge
        self.total_delay_time = 0
        # Blocked out this part of the code
        # # TODO
        # self.delay_time = self.random.randrange(0, 10)
        # print(self.delay_time)
        # this is supposed to be at bridge level so when making a bridge it has to be broken/not, not everytime the function delay time gets called
        # if it can not find bridge_prob, then use A:, B: c: etc
        probs = getattr(self.model, 'bridge_probabilities', {'A': 0, 'B': 0, 'C': 0, 'D': 0})
        breakdown_chance = probs.get(self.condition, 0.0)

        # Roll a random number between 0.0 and 1.0.
        # If it's less than our breakdown chance, the bridge is broken!
        if self.random.random() < (breakdown_chance / 100.0):  # Dividing by 100 if you input percentages like 5, 10, 20
            self.is_broken = True
        else:
            self.is_broken = False

    # Added this method
    # TODO

    def get_delay_time(self):
        """
        Calculates the delay time for a truck based on bridge length,
        only if the bridge breaks down according to its condition probability.
        """

        if self.is_broken:
            # Assign the value to 'delay' instead of returning it immediately
            if self.length > 200:
                delay = int(self.random.triangular(60, 240, 120))
            elif self.length >= 50:
                delay = self.random.randint(45, 90)
            elif self.length >= 10:
                delay = self.random.randint(15, 60)
            else:
                delay = self.random.randint(10, 20)

            # NEW for BONUS: Add this truck's delay to the bridge's stopwatch
            self.total_delay_time += delay

            # Now we can return it!
            return delay
        else:
            # If the random number is higher, the bridge is fine. No delay.
            return 0


# ---------------------------------------------------------------
class Link(Infra):
    pass


# ---------------------------------------------------------------
class Intersection(Infra):
    pass


# ---------------------------------------------------------------
class Sink(Infra):
    """
    Sink removes vehicles

    Attributes
    __________
    vehicle_removed_toggle: bool
        toggles each time when a vehicle is removed
    ...

    """
    vehicle_removed_toggle = False

    def remove(self, vehicle):
        self.model.schedule.remove(vehicle)
        self.vehicle_removed_toggle = not self.vehicle_removed_toggle
        # print(str(self) + ' REMOVE ' + str(vehicle))


# ---------------------------------------------------------------

class Source(Infra):
    """
    Source generates vehicles

    Class Attributes:
    -----------------
    truck_counter : int
        the number of trucks generated by ALL sources. Used as Truck ID!

    Attributes
    __________
    generation_frequency: int
        the frequency (the number of ticks) by which a truck is generated

    vehicle_generated_flag: bool
        True when a Truck is generated in this tick; False otherwise
    ...

    """

    truck_counter = 0
    generation_frequency = 5
    vehicle_generated_flag = False

    def step(self):
        if self.model.schedule.steps % self.generation_frequency == 0:
            self.generate_truck()
        else:
            self.vehicle_generated_flag = False

    def generate_truck(self):
        """
        Generates a truck, sets its path, increases the global and local counters
        """
        try:
            agent = Vehicle('Truck' + str(Source.truck_counter), self.model, self)
            if agent:
                self.model.schedule.add(agent)
                agent.set_path()
                Source.truck_counter += 1
                self.vehicle_count += 1
                self.vehicle_generated_flag = True
                # print(str(self) + " GENERATE " + str(agent))
        except Exception as e:
            print("Oops!", e.__class__, "occurred.")


# ---------------------------------------------------------------
class SourceSink(Source, Sink):
    """
    Generates and removes trucks
    """
    pass


# ---------------------------------------------------------------
class Vehicle(Agent):
    """

    Attributes
    __________
    speed: float
        speed in meter per minute (m/min)

    step_time: int
        the number of minutes (or seconds) a tick represents
        Used as a base to change unites

    state: Enum (DRIVE | WAIT)
        state of the vehicle

    location: Infra
        reference to the Infra where the vehicle is located

    location_offset: float
        the location offset in meters relative to the starting point of
        the Infra, which has a certain length
        i.e. location_offset < length

    path_ids: Series
        the whole path (origin and destination) where the vehicle shall drive
        It consists the Infras' uniques IDs in a sequential order

    location_index: int
        a pointer to the current Infra in "path_ids" (above)
        i.e. the id of self.location is self.path_ids[self.location_index]

    waiting_time: int
        the time the vehicle needs to wait

    generated_at_step: int
        the timestamp (number of ticks) that the vehicle is generated

    removed_at_step: int
        the timestamp (number of ticks) that the vehicle is removed
    ...

    """

    # 48 km/h translated into meter per min
    speed = 48 * 1000 / 60
    # One tick represents 1 minute
    step_time = 1

    class State(Enum):
        DRIVE = 1
        WAIT = 2

    def __init__(self, unique_id, model, generated_by,
                 location_offset=0, path_ids=None):
        super().__init__(unique_id, model)
        self.generated_by = generated_by
        self.generated_at_step = model.schedule.steps
        self.location = generated_by
        self.location_offset = location_offset
        self.pos = generated_by.pos
        self.path_ids = path_ids
        # default values
        self.state = Vehicle.State.DRIVE
        self.location_index = 0
        self.waiting_time = 0
        self.waited_at = None
        self.removed_at_step = None

    def __str__(self):
        return "Vehicle" + str(self.unique_id) + \
            " +" + str(self.generated_at_step) + " -" + str(self.removed_at_step) + \
            " " + str(self.state) + '(' + str(self.waiting_time) + ') ' + \
            str(self.location) + '(' + str(self.location.vehicle_count) + ') ' + str(self.location_offset)

    def set_path(self):
        """
        Set the origin destination path of the vehicle
        """
        self.path_ids = self.model.get_route(self.generated_by.unique_id)

    def step(self):
        """
        Vehicle waits or drives at each step
        """
        if self.state == Vehicle.State.WAIT:
            self.waiting_time = max(self.waiting_time - 1, 0)
            if self.waiting_time == 0:
                self.waited_at = self.location
                self.state = Vehicle.State.DRIVE

        if self.state == Vehicle.State.DRIVE:
            self.drive()

        """
        To print the vehicle trajectory at each step
        """
        # print(self)

    def drive(self):

        # the distance that vehicle drives in a tick
        # speed is global now: can change to instance object when individual speed is needed
        distance = Vehicle.speed * Vehicle.step_time
        distance_rest = self.location_offset + distance - self.location.length

        if distance_rest > 0:
            # go to the next object
            self.drive_to_next(distance_rest)
        else:
            # remain on the same object
            self.location_offset += distance

    def drive_to_next(self, distance):
        """
        vehicle shall move to the next object with the given distance
        """

    def drive_to_next(self, distance):
        """
        vehicle shall move to the next object with the given distance
        """
        # New safety:
        # Check of we niet over de grens van onze route-lijst heen schieten
        if self.location_index >= len(self.path_ids) - 1:
            # Als de lijst op is, halen we de truck uit de simulatie
            if self.location:
                self.location.vehicle_count -= 1
            self.model.schedule.remove(self)
            return

        # old code as in ass2
        self.location_index += 1
        next_id = self.path_ids[self.location_index]
        next_infra = self.model.G.nodes[next_id]['agent_object']

        if isinstance(next_infra, Sink):
            self.arrive_at_next(next_infra, 0)
            self.removed_at_step = self.model.schedule.steps

            # Je hebt gecheckt dat het generated_at_step is, dus dit is top!
            travel_time = self.removed_at_step - self.generated_at_step
            self.model.travel_times.append(travel_time)

            self.location.remove(self)
            return

        elif isinstance(next_infra, Bridge):
            self.waiting_time = next_infra.get_delay_time()
            if self.waiting_time > 0:
                self.arrive_at_next(next_infra, 0)
                self.state = Vehicle.State.WAIT
                return

        if next_infra.length > distance:
            self.arrive_at_next(next_infra, distance)
        else:
            self.drive_to_next(distance - next_infra.length)

    def arrive_at_next(self, next_infra, location_offset):
        """
        Arrive at next_infra with the given location_offset
        """
        self.location.vehicle_count -= 1
        self.location = next_infra
        self.location_offset = location_offset
        self.location.vehicle_count += 1

# EOF -----------------------------------------------------------
